# Generated by Django 5.2.1 on 2025-05-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idEspecie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('informacionNutricional', models.CharField(max_length=100)),
                ('tasaCrecimiento', models.CharField(max_length=45)),
                ('tasaReproduccion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'Especie',
            },
        ),
        migrations.CreateModel(
            name='Estanque',
            fields=[
                ('idEstanque', models.AutoField(primary_key=True, serialize=False)),
                ('litros', models.IntegerField()),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estanque',
                'verbose_name_plural': 'Estanques',
                'db_table': 'Estanque',
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('idFinca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'db_table': 'Finca',
            },
        ),
        migrations.CreateModel(
            name='MetodoAcuicola',
            fields=[
                ('idMetodoAcuicola', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Método Acuícola',
                'verbose_name_plural': 'Métodos Acuícolas',
                'db_table': 'MetodoAcuicola',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('idSensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSensor', models.CharField(max_length=45)),
                ('unidadMedida', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'db_table': 'Sensor',
            },
        ),
        migrations.CreateModel(
            name='TipoEstanque',
            fields=[
                ('idTipoEstanque', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Estanque',
                'verbose_name_plural': 'Tipos de Estanque',
                'db_table': 'TipoEstanque',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'TipoUsuario',
            },
        ),
        migrations.CreateModel(
            name='BitacoraDesdoble',
            fields=[
                ('idBitacoraDesdoble', models.AutoField(primary_key=True, serialize=False)),
                ('fechaModificacion', models.DateTimeField()),
                ('cambioRealizado', models.TextField()),
                ('idEstanque', models.ForeignKey(db_column='idEstanque', on_delete=django.db.models.deletion.CASCADE, to='api.estanque')),
            ],
            options={
                'verbose_name': 'Bitácora de Desdoble',
                'verbose_name_plural': 'Bitácoras de Desdoble',
                'db_table': 'BitacoraDesdoble',
            },
        ),
        migrations.AddField(
            model_name='estanque',
            name='idFinca',
            field=models.ForeignKey(db_column='idFinca', on_delete=django.db.models.deletion.CASCADE, to='api.finca'),
        ),
        migrations.CreateModel(
            name='HistorialEstanques',
            fields=[
                ('idHistorialEstanques', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cambioRealizado', models.TextField()),
                ('idEstanque', models.ForeignKey(db_column='idEstanque', on_delete=django.db.models.deletion.CASCADE, to='api.estanque')),
            ],
            options={
                'verbose_name': 'Historial de Estanque',
                'verbose_name_plural': 'Historiales de Estanque',
                'db_table': 'HistorialEstanques',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idEspecie', models.ForeignKey(db_column='idEspecie', on_delete=django.db.models.deletion.CASCADE, to='api.especie')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'Inventario',
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='idMetodoAcuicola',
            field=models.ForeignKey(db_column='idMetodoAcuicola', on_delete=django.db.models.deletion.CASCADE, to='api.metodoacuicola'),
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('idMonitoreo', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('idEstanque', models.ForeignKey(db_column='idEstanque', on_delete=django.db.models.deletion.CASCADE, to='api.estanque')),
                ('idSensor', models.ForeignKey(db_column='idSensor', on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
            options={
                'verbose_name': 'Monitoreo',
                'verbose_name_plural': 'Monitoreos',
                'db_table': 'Monitoreo',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idAlerta', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(max_length=45)),
                ('idMonitoreo', models.ForeignKey(db_column='idMonitoreo', on_delete=django.db.models.deletion.CASCADE, to='api.monitoreo')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'Alerta',
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('idSiembra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('inversion', models.FloatField()),
                ('idEspecie', models.ForeignKey(db_column='idEspecie', on_delete=django.db.models.deletion.CASCADE, to='api.especie')),
                ('idEstanque', models.ForeignKey(db_column='idEstanque', on_delete=django.db.models.deletion.CASCADE, to='api.estanque')),
            ],
            options={
                'verbose_name': 'Siembra',
                'verbose_name_plural': 'Siembras',
                'db_table': 'Siembra',
            },
        ),
        migrations.CreateModel(
            name='HistorialSiembra',
            fields=[
                ('idHistorialSiembra', models.AutoField(primary_key=True, serialize=False)),
                ('fechaComercializacion', models.DateTimeField()),
                ('kilosVendidos', models.IntegerField()),
                ('precioVenta', models.FloatField()),
                ('tasaMortandad', models.FloatField()),
                ('idSiembra', models.ForeignKey(db_column='idSiembra', on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'verbose_name': 'Historial de Siembra',
                'verbose_name_plural': 'Historiales de Siembra',
                'db_table': 'HistorialSiembra',
            },
        ),
        migrations.CreateModel(
            name='Desdoble',
            fields=[
                ('idDesdoble', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('idEstanqueDestino', models.ForeignKey(db_column='idEstanqueDestino', on_delete=django.db.models.deletion.CASCADE, related_name='desdobles_destino', to='api.estanque')),
                ('idEstanqueOrigen', models.ForeignKey(db_column='idEstanqueOrigen', on_delete=django.db.models.deletion.CASCADE, related_name='desdobles_origen', to='api.estanque')),
                ('idSiembra', models.ForeignKey(db_column='idSiembra', on_delete=django.db.models.deletion.CASCADE, to='api.siembra')),
            ],
            options={
                'verbose_name': 'Desdoble',
                'verbose_name_plural': 'Desdobles',
                'db_table': 'Desdoble',
            },
        ),
        migrations.AddField(
            model_name='estanque',
            name='idTipoEstanque',
            field=models.ForeignKey(db_column='idTipoEstanque', on_delete=django.db.models.deletion.CASCADE, to='api.tipoestanque'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=100)),
                ('idTipoUsuario', models.ForeignKey(db_column='idTipoUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='idUsuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='api.usuario'),
        ),
    ]
