# Generated by Django 5.2.1 on 2025-05-22 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_informacionnutricional_tasacrecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialsiembra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Comercialización'), ('COMERCIALIZADO', 'Comercializado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', help_text='Estado del historial de siembra', max_length=20),
        ),
        migrations.AddField(
            model_name='historialsiembra',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización del registro'),
        ),
        migrations.AddField(
            model_name='historialsiembra',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación del registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialsiembra',
            name='kiloPorPez',
            field=models.FloatField(blank=True, help_text='Peso promedio por pez al momento de la venta (en kg)', null=True),
        ),
        migrations.AddField(
            model_name='historialsiembra',
            name='pecesComercializados',
            field=models.IntegerField(blank=True, help_text='Número de peces al momento de comercialización (calculado)', null=True),
        ),
        migrations.AddField(
            model_name='historialsiembra',
            name='totalKilos',
            field=models.FloatField(blank=True, help_text='Total de kilos de la cosecha', null=True),
        ),
        migrations.AlterField(
            model_name='historialsiembra',
            name='fechaComercializacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de comercialización - se completa al vender', null=True),
        ),
        migrations.AlterField(
            model_name='historialsiembra',
            name='kilosVendidos',
            field=models.FloatField(default=0, help_text='Total de kilos vendidos'),
        ),
        migrations.AlterField(
            model_name='historialsiembra',
            name='precioVenta',
            field=models.FloatField(default=0, help_text='Precio de venta por kilo'),
        ),
        migrations.AlterField(
            model_name='historialsiembra',
            name='tasaMortandad',
            field=models.FloatField(blank=True, help_text='Tasa de mortandad calculada automáticamente (%)', null=True),
        ),
    ]
