# Generated by Django 5.2.1 on 2025-05-22 18:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historialsiembra_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoradesdoble',
            name='fechaModificacion',
        ),
        migrations.RemoveField(
            model_name='bitacoradesdoble',
            name='idEstanque',
        ),
        migrations.AddField(
            model_name='alerta',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de creación de la alerta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='fechaResolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha de resolución de la alerta', null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='idEspecie',
            field=models.ForeignKey(blank=True, db_column='idEspecie', help_text='Especie que causó la alerta', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.especie'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipoAlerta',
            field=models.CharField(choices=[('TEMPERATURA', 'Temperatura Anómala'), ('PH', 'pH Anómalo'), ('OXIGENO', 'Oxígeno Anómalo'), ('OTRO', 'Otro Tipo de Alerta')], default='OTRO', help_text='Tipo de alerta generada', max_length=20),
        ),
        migrations.AddField(
            model_name='alerta',
            name='valorLimite',
            field=models.FloatField(default=0.0, help_text='Valor límite que se excedió'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='valorMedido',
            field=models.FloatField(default=0, help_text='Valor que causó la alerta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacoradesdoble',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha automática cuando se crea el desdoble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitacoradesdoble',
            name='idDesdoble',
            field=models.ForeignKey(db_column='idDesdoble', default=1, help_text='Desdoble relacionado', on_delete=django.db.models.deletion.CASCADE, to='api.desdoble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='fechaActualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización del inventario'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='idFinca',
            field=models.ForeignKey(db_column='idFinca', default=1, help_text='Finca donde está el inventario', on_delete=django.db.models.deletion.CASCADE, to='api.finca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Alerta Activa'), ('RESUELTA', 'Alerta Resuelta'), ('IGNORADA', 'Alerta Ignorada')], default='ACTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(help_text='Mensaje descriptivo de la alerta'),
        ),
        migrations.AlterField(
            model_name='bitacoradesdoble',
            name='cambioRealizado',
            field=models.TextField(blank=True, help_text='Descripción opcional del cambio realizado', null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0, help_text='Cantidad actual de peces de esta especie en la finca'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('idEspecie', 'idFinca')},
        ),
    ]
